### ISSUE TITLE
WanImageToVideo_F2 'WanVAE' object has no attribute 'clear_cache'

### ISSUE THREAD

**Issue by loliaddict** [comfyanonymous/ComfyUI#10221]
### Custom Node Testing

- [ ] I have tried disabling custom nodes and the issue persists (see [how to disable custom nodes](https://docs.comfy.org/troubleshooting/custom-node-issues#step-1%3A-test-with-all-custom-nodes-disabled) if you need help)

### Expected Behavior

Produce a video

### Actual Behavior

Im trying to run wan 2.1. I have ran it perfectly fine before, I have no idea why it's not working, I've reinstalled the wan vae from multiple sources multiple times and it fails regardless

### Steps to Reproduce

Run wan 2.1 img2vid

### Debug Logs

```powershell
# ComfyUI Error Report
## Error Details
- **Node ID:** 461
- **Node Type:** WanImageToVideo_F2
- **Exception Type:** AttributeError
- **Exception Message:** 'WanVAE' object has no attribute 'clear_cache'

## Stack Trace

  File "/workspace/ComfyUI/execution.py", line 496, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/workspace/ComfyUI/execution.py", line 315, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/workspace/ComfyUI/execution.py", line 289, in _async_map_node_over_list
    await process_inputs(input_dict, i)

  File "/workspace/ComfyUI/execution.py", line 277, in process_inputs
    result = f(**inputs)
             ^^^^^^^^^^^

  File "/workspace/ComfyUI/custom_nodes/ComfyUI-WanStartEndFramesNative/nodes/nodes.py", line 110, in initialize
    la = vae.encode(concatenated)
         ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/workspace/ComfyUI/comfy/sd.py", line 739, in encode
    out = self.first_stage_model.encode(pixels_in).to(self.output_device).float()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/workspace/ComfyUI/custom_nodes/ComfyUI-WanStartEndFramesNative/nodes/nodes.py", line 14, in encode
    self.clear_cache()
    ^^^^^^^^^^^^^^^^

  File "/workspace/venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1962, in __getattr__
    raise AttributeError(


## System Information
- **ComfyUI Version:** 0.3.62
- **Arguments:** main.py --preview-method auto --use-sage-attention --listen 0.0.0.0 --port 8188
- **OS:** posix
- **Python Version:** 3.11.11 (main, Dec  4 2024, 08:55:07) [GCC 11.4.0]
- **Embedded Python:** false
- **PyTorch Version:** 2.8.0+cu128
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 25262096384
  - **VRAM Free:** 24849874944
  - **Torch VRAM Total:** 0
  - **Torch VRAM Free:** 0

## Logs

2025-10-05T17:08:32.543113 - [START] Security scan2025-10-05T17:08:32.543130 - 
2025-10-05T17:08:32.637650 - [ComfyUI-Manager] Using uv as Python module for pip operations.
2025-10-05T17:08:33.431921 - [DONE] Security scan2025-10-05T17:08:33.431934 - 
2025-10-05T17:08:33.861071 - ## ComfyUI-Manager: installing dependencies done.2025-10-05T17:08:33.861115 - 
2025-10-05T17:08:33.861162 - ** ComfyUI startup time:2025-10-05T17:08:33.861212 -  2025-10-05T17:08:33.861241 - 2025-10-05 17:08:33.8612025-10-05T17:08:33.861275 - 
2025-10-05T17:08:33.861319 - ** Platform:2025-10-05T17:08:33.861375 -  2025-10-05T17:08:33.861404 - Linux2025-10-05T17:08:33.861431 - 
2025-10-05T17:08:33.861456 - ** Python version:2025-10-05T17:08:33.861508 -  2025-10-05T17:08:33.861530 - 3.11.11 (main, Dec  4 2024, 08:55:07) [GCC 11.4.0]2025-10-05T17:08:33.861557 - 
2025-10-05T17:08:33.861584 - ** Python executable:2025-10-05T17:08:33.861607 -  2025-10-05T17:08:33.861640 - /workspace/venv/bin/python32025-10-05T17:08:33.861673 - 
2025-10-05T17:08:33.861700 - ** ComfyUI Path:2025-10-05T17:08:33.861723 -  2025-10-05T17:08:33.861775 - /workspace/ComfyUI2025-10-05T17:08:33.861803 - 
2025-10-05T17:08:33.861829 - ** ComfyUI Base Folder Path:2025-10-05T17:08:33.861851 -  2025-10-05T17:08:33.861902 - /workspace/ComfyUI2025-10-05T17:08:33.861926 - 
2025-10-05T17:08:33.861954 - ** User directory:2025-10-05T17:08:33.861978 -  2025-10-05T17:08:33.862011 - /workspace/ComfyUI/user2025-10-05T17:08:33.862035 - 
2025-10-05T17:08:33.862064 - ** ComfyUI-Manager config path:2025-10-05T17:08:33.862091 -  2025-10-05T17:08:33.862112 - /workspace/ComfyUI/user/default/ComfyUI-Manager/config.ini2025-10-05T17:08:33.862143 - 
2025-10-05T17:08:33.862168 - ** Log path:2025-10-05T17:08:33.862192 -  2025-10-05T17:08:33.862213 - /workspace/ComfyUI/user/comfyui.log2025-10-05T17:08:33.862237 - 
2025-10-05T17:08:34.696822 - 
Prestartup times for custom nodes:
2025-10-05T17:08:34.696941 -    0.0 seconds: /workspace/ComfyUI/custom_nodes/rgthree-comfy
2025-10-05T17:08:34.697040 -    0.0 seconds: /workspace/ComfyUI/custom_nodes/comfyui-easy-use
2025-10-05T17:08:34.697113 -    3.8 seconds: /workspace/ComfyUI/custom_nodes/comfyui-manager
2025-10-05T17:08:34.697159 - 
2025-10-05T17:08:48.241409 - Checkpoint files will always be loaded safely.
2025-10-05T17:08:48.544446 - Total VRAM 24092 MB, total RAM 192326 MB
2025-10-05T17:08:48.544571 - pytorch version: 2.8.0+cu128
2025-10-05T17:08:48.546078 - Set vram state to: NORMAL_VRAM
2025-10-05T17:08:48.546365 - Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
2025-10-05T17:08:59.376685 - Using sage attention
2025-10-05T17:09:19.946596 - Python version: 3.11.11 (main, Dec  4 2024, 08:55:07) [GCC 11.4.0]
2025-10-05T17:09:19.946945 - ComfyUI version: 0.3.62
2025-10-05T17:09:19.957722 - ComfyUI frontend version: 1.27.7
2025-10-05T17:09:19.965909 - [Prompt Server] web root: /workspace/venv/lib/python3.11/site-packages/comfyui_frontend_package/static
2025-10-05T17:09:27.829582 - ComfyUI-GGUF: Allowing full torch compile
2025-10-05T17:09:28.128399 - 
2025-10-05T17:09:28.128467 - [92m[rgthree-comfy] Loaded 48 exciting nodes. 🎉[0m2025-10-05T17:09:28.128499 - 
2025-10-05T17:09:28.128553 - 
2025-10-05T17:09:37.237311 - [34m[ComfyUI-Easy-Use] server: [0mv1.3.3 [92mLoaded[0m2025-10-05T17:09:37.237354 - 
2025-10-05T17:09:37.237386 - [34m[ComfyUI-Easy-Use] web root: [0m/workspace/ComfyUI/custom_nodes/comfyui-easy-use/web_version/v2 [92mLoaded[0m2025-10-05T17:09:37.237414 - 
2025-10-05T17:09:38.024951 - ### Loading: ComfyUI-Manager (V3.37)
2025-10-05T17:09:38.028645 - [ComfyUI-Manager] network_mode: public
2025-10-05T17:09:38.028812 - [ComfyUI-Manager] Since --preview-method is set, ComfyUI-Manager's preview method feature will be ignored.
2025-10-05T17:09:38.220316 - ### ComfyUI Version: v0.3.62-32-gb1fa1922 | Released on '2025-10-04'
2025-10-05T17:09:38.317269 - 
Import times for custom nodes:
2025-10-05T17:09:38.317332 -    0.0 seconds: /workspace/ComfyUI/custom_nodes/comfyui-mxtoolkit
2025-10-05T17:09:38.317411 -    0.0 seconds: /workspace/ComfyUI/custom_nodes/ComfyUI-WanStartEndFramesNative
2025-10-05T17:09:38.317448 -    0.1 seconds: /workspace/ComfyUI/custom_nodes/comfyui_essentials
2025-10-05T17:09:38.317487 -    0.1 seconds: /workspace/ComfyUI/custom_nodes/comfyui-custom-scripts
2025-10-05T17:09:38.317517 -    0.1 seconds: /workspace/ComfyUI/custom_nodes/ComfyUI-GGUF
2025-10-05T17:09:38.317574 -    0.2 seconds: /workspace/ComfyUI/custom_nodes/comfyui-frame-interpolation
2025-10-05T17:09:38.317605 -    0.2 seconds: /workspace/ComfyUI/custom_nodes/comfyui-various
2025-10-05T17:09:38.317635 -    0.3 seconds: /workspace/ComfyUI/custom_nodes/comfyui-videohelpersuite
2025-10-05T17:09:38.317681 -    0.3 seconds: /workspace/ComfyUI/custom_nodes/rgthree-comfy
2025-10-05T17:09:38.317729 -    0.3 seconds: /workspace/ComfyUI/custom_nodes/comfyui-manager
2025-10-05T17:09:38.317756 -    1.0 seconds: /workspace/ComfyUI/custom_nodes/comfyui-kjnodes
2025-10-05T17:09:38.317785 -    9.1 seconds: /workspace/ComfyUI/custom_nodes/comfyui-easy-use
2025-10-05T17:09:38.317814 - 
2025-10-05T17:09:38.384486 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
2025-10-05T17:09:38.416595 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
2025-10-05T17:09:38.444088 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
2025-10-05T17:09:38.484034 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
2025-10-05T17:09:38.576493 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
2025-10-05T17:09:39.941503 - Context impl SQLiteImpl.
2025-10-05T17:09:39.941651 - Will assume non-transactional DDL.
2025-10-05T17:09:39.948036 - No target revision found.
2025-10-05T17:09:40.178341 - Starting server

2025-10-05T17:09:40.178545 - To see the GUI go to: http://0.0.0.0:8188
2025-10-05T17:09:41.803921 - FETCH ComfyRegistry Data: 5/992025-10-05T17:09:41.804014 - 
2025-10-05T17:09:45.717273 - FETCH ComfyRegistry Data: 10/992025-10-05T17:09:45.717382 - 
2025-10-05T17:09:49.392728 - FETCH ComfyRegistry Data: 15/992025-10-05T17:09:49.392872 - 
2025-10-05T17:09:53.120947 - FETCH ComfyRegistry Data: 20/992025-10-05T17:09:53.121062 - 
2025-10-05T17:09:56.656034 - FETCH ComfyRegistry Data: 25/992025-10-05T17:09:56.656172 - 
2025-10-05T17:10:00.333000 - FETCH ComfyRegistry Data: 30/992025-10-05T17:10:00.333077 - 
2025-10-05T17:10:03.006195 - got prompt
2025-10-05T17:10:03.511277 - Using pytorch attention in VAE
2025-10-05T17:10:03.511933 - Using pytorch attention in VAE
2025-10-05T17:10:04.658483 - FETCH ComfyRegistry Data: 35/992025-10-05T17:10:04.658550 - 
2025-10-05T17:10:05.235012 - VAE load device: cuda:0, offload device: cpu, dtype: torch.bfloat16
2025-10-05T17:10:08.499893 - FETCH ComfyRegistry Data: 40/992025-10-05T17:10:08.499951 - 
2025-10-05T17:10:12.115083 - FETCH ComfyRegistry Data: 45/992025-10-05T17:10:12.115149 - 
2025-10-05T17:10:15.698044 - FETCH ComfyRegistry Data: 50/992025-10-05T17:10:15.698105 - 
2025-10-05T17:10:15.867881 - Requested to load CLIPVisionModelProjection
2025-10-05T17:10:16.004781 - loaded completely 22479.4875 1208.09814453125 True
2025-10-05T17:10:20.048921 - CLIP/text encoder model load device: cuda:0, offload device: cpu, current: cpu, dtype: torch.float16
2025-10-05T17:10:20.052127 - Requested to load WanTEModel
2025-10-05T17:10:21.464193 - FETCH ComfyRegistry Data: 55/992025-10-05T17:10:21.464265 - 
2025-10-05T17:10:25.831544 - FETCH ComfyRegistry Data: 60/992025-10-05T17:10:25.831620 - 
2025-10-05T17:10:30.332401 - FETCH ComfyRegistry Data: 65/992025-10-05T17:10:30.332462 - 
2025-10-05T17:10:33.835895 - FETCH ComfyRegistry Data: 70/992025-10-05T17:10:33.835976 - 
2025-10-05T17:10:37.492064 - FETCH ComfyRegistry Data: 75/992025-10-05T17:10:37.492172 - 
2025-10-05T17:10:41.257478 - FETCH ComfyRegistry Data: 80/992025-10-05T17:10:41.257520 - 
2025-10-05T17:10:45.220688 - FETCH ComfyRegistry Data: 85/992025-10-05T17:10:45.220753 - 
2025-10-05T17:10:49.081167 - FETCH ComfyRegistry Data: 90/992025-10-05T17:10:49.081216 - 
2025-10-05T17:10:52.921213 - FETCH ComfyRegistry Data: 95/992025-10-05T17:10:52.921262 - 
2025-10-05T17:10:55.328374 - loaded completely 21169.2619140625 10835.4765625 True
2025-10-05T17:10:56.230564 - Requested to load WanVAE
2025-10-05T17:10:56.257256 - loaded completely 2254.0595664978027 242.02829551696777 True
2025-10-05T17:10:56.514326 - FETCH ComfyRegistry Data [DONE]2025-10-05T17:10:56.514565 - 
2025-10-05T17:10:56.554249 - !!! Exception during processing !!! 'WanVAE' object has no attribute 'clear_cache'
2025-10-05T17:10:56.581427 - Traceback (most recent call last):
  File "/workspace/ComfyUI/execution.py", line 496, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/ComfyUI/execution.py", line 315, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/ComfyUI/execution.py", line 289, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "/workspace/ComfyUI/execution.py", line 277, in process_inputs
    result = f(**inputs)
             ^^^^^^^^^^^
  File "/workspace/ComfyUI/custom_nodes/ComfyUI-WanStartEndFramesNative/nodes/nodes.py", line 110, in initialize
    la = vae.encode(concatenated)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/ComfyUI/comfy/sd.py", line 739, in encode
    out = self.first_stage_model.encode(pixels_in).to(self.output_device).float()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/ComfyUI/custom_nodes/ComfyUI-WanStartEndFramesNative/nodes/nodes.py", line 14, in encode
    self.clear_cache()
    ^^^^^^^^^^^^^^^^
  File "/workspace/venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1962, in __getattr__
    raise AttributeError(
AttributeError: 'WanVAE' object has no attribute 'clear_cache'

2025-10-05T17:10:56.583366 - [ComfyUI-Manager] default cache updated: https://api.comfy.org/nodes
2025-10-05T17:10:56.584478 - Prompt executed in 53.35 seconds
2025-10-05T17:10:56.869739 - FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json2025-10-05T17:10:56.869759 - 2025-10-05T17:10:57.063234 -  [DONE]2025-10-05T17:10:57.063333 - 
2025-10-05T17:10:57.106075 - [ComfyUI-Manager] All startup tasks have been completed.


## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.

Workflow too large. Please manually upload the workflow from local file system.


## Additional Context
(Please add any additional context or steps to reproduce the error here)
```

**Comment by loliaddict** [comment]
Fixed after updating comfyui

**Comment by rafaelfabres** [comment]
I have this problem now and my comfyui is up to date

**Comment by DeepSeaCatz** [comment]
Had this problem and I am was sure I had the latest update. I updated Comfy once more and it worked.
I am thinking that restarting Comfy is what fix my issue.

**Comment by DeepSeaCatz** [comment]
Hmm it keeps happening again randomly. Only way now is to always update comfy, even at latest update and then start queue. Annoying.

**Comment by Valarxx** [comment]
> Hmm it keeps happening again randomly. Only way now is to always update comfy, even at latest update and then start queue. Annoying.

I applyed changes from [this](https://github.com/Flow-two/ComfyUI-WanStartEndFramesNative/commit/24554d329e405aa27b9c9828c4621491f1106b51) commit and it fixed bug for me. Why it's closed, problem is still actual and that commit fixes the problem.

**Comment by flashosophy** [comment]
the link from Valaraxx worked for me
