### ISSUE TITLE
privateuseone is not supported for torch.Generator()

### ISSUE THREAD

**Issue by drago87** [comfyanonymous/ComfyUI#1707]
I'm getting this error when using the defult workflow with the samplers
dpmpp_sde_gpu
dpmpp_2m_sde_gpu
dpmpp_3m_sde_gpu
the outher samplers i have tried have worked
i have a AMD Radeon RX 5700 XT 8GB memory and 16gb shared memory

> Error occurred when executing KSampler:
> 
> Device type privateuseone is not supported for torch.Generator() api.
> 
> File "D:\AI\ComfyUI_AMD\ComfyUI\execution.py", line 152, in recursive_execute
> output_data, output_ui = get_output_data(obj, input_data_all)
> File "D:\AI\ComfyUI_AMD\ComfyUI\execution.py", line 82, in get_output_data
> return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
> File "D:\AI\ComfyUI_AMD\ComfyUI\execution.py", line 75, in map_node_over_list
> results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
> File "D:\AI\ComfyUI_AMD\ComfyUI\nodes.py", line 1236, in sample
> return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
> File "D:\AI\ComfyUI_AMD\ComfyUI\nodes.py", line 1206, in common_ksampler
> samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
> File "D:\AI\ComfyUI_AMD\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\sample_error_enhancer.py", line 22, in informative_sample
> raise e
> File "D:\AI\ComfyUI_AMD\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\sample_error_enhancer.py", line 9, in informative_sample
> return original_sample(*args, **kwargs)
> File "D:\AI\ComfyUI_AMD\ComfyUI\comfy\sample.py", line 97, in sample
> samples = sampler.sample(noise, positive_copy, negative_copy, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
> File "D:\AI\ComfyUI_AMD\ComfyUI\comfy\samplers.py", line 785, in sample
> return sample(self.model, noise, positive, negative, cfg, self.device, sampler(), sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
> File "D:\AI\ComfyUI_AMD\ComfyUI\comfy\samplers.py", line 690, in sample
> samples = sampler.sample(model_wrap, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
> File "D:\AI\ComfyUI_AMD\ComfyUI\comfy\samplers.py", line 630, in sample
> samples = getattr(k_diffusion_sampling, "sample_{}".format(sampler_name))(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **extra_options)
> File "C:\Users\Drago87\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
> return func(*args, **kwargs)
> File "D:\AI\ComfyUI_AMD\ComfyUI\comfy\k_diffusion\sampling.py", line 706, in sample_dpmpp_sde_gpu
> noise_sampler = BrownianTreeNoiseSampler(x, sigma_min, sigma_max, seed=extra_args.get("seed", None), cpu=False) if noise_sampler is None else noise_sampler
> File "D:\AI\ComfyUI_AMD\ComfyUI\comfy\k_diffusion\sampling.py", line 119, in __init__
> self.tree = BatchedBrownianTree(x, t0, t1, seed, cpu=cpu)
> File "D:\AI\ComfyUI_AMD\ComfyUI\comfy\k_diffusion\sampling.py", line 85, in __init__
> self.trees = [torchsde.BrownianTree(t0, w0, t1, entropy=s, **kwargs) for s in seed]
> File "D:\AI\ComfyUI_AMD\ComfyUI\comfy\k_diffusion\sampling.py", line 85, in
> self.trees = [torchsde.BrownianTree(t0, w0, t1, entropy=s, **kwargs) for s in seed]
> File "C:\Users\Drago87\AppData\Local\Programs\Python\Python310\lib\site-packages\torchsde\_brownian\derived.py", line 155, in __init__
> self._interval = brownian_interval.BrownianInterval(t0=t0,
> File "C:\Users\Drago87\AppData\Local\Programs\Python\Python310\lib\site-packages\torchsde\_brownian\brownian_interval.py", line 554, in __init__
> W = self._randn(initial_W_seed) * math.sqrt(t1 - t0)
> File "C:\Users\Drago87\AppData\Local\Programs\Python\Python310\lib\site-packages\torchsde\_brownian\brownian_interval.py", line 248, in _randn
> return _randn(size, self._top._dtype, self._top._device, seed)
> File "C:\Users\Drago87\AppData\Local\Programs\Python\Python310\lib\site-packages\torchsde\_brownian\brownian_interval.py", line 31, in _randn
> generator = torch.Generator(device).manual_seed(int(seed))

**Comment by NeedsMoar** [comment]
That's expected.   DirectML (as you might guess from the name of the device being privateuseone) is a kinda ugly hack to make things work on top of torch that MS isn't really developing very heavily so some things like the GPU samplers and multiple extensions won't work.  The _gpu versions of these samplers are faster than the non _gpu normally but DML isn't really fast enough to see the gain from generating them on-device vs on cpu IMO.

**Comment by drago87** [comment]
Ok

**Comment by patientx** [comment]
I have 6600 and having the same problem with a lot of extensions, codeformer for example, and some control.net features too. The thing is the same torch-directml version (which seems to come out on april last) along with same torch and torchvision ; is also present in sdwebui and all these problems are solved there , face swapping, those controlnet, ipadapter features also work without problems there. One comfyui extension causing this was reactor (which is using codeformer) and I asked the author about this problem, he told me to use torch 2.0.1 BUT directml only works with 2.0 and the same extension works with 2.0 on sdwebui without any problem so there is something different in comfyui overall that is causing this ?

**Comment by jick-nice** [comment]
My graphics card is AMD6700xt and I get an error when I run it, It's:" Device type privateuseone is not supported for torch. Generator() api. "Do you have any solution, thank you very much!

**Comment by TheSloppiestOfJoes** [comment]
This fixed the issue for me:

Go into your-venv-directory\Lib\site-packages\torchsde\_brownian

In brownian_interval.py, edit line 31 from

```
generator = torch.Generator(device).manual_seed(int(seed))
```

to

```
generator = torch.Generator().manual_seed(int(seed))
```

ComfyUI should now generate correctly.

**Comment by aelfwyne** [comment]
> This fixed the issue for me:
> 
> Go into your-venv-directory\Lib\site-packages\torchsde_brownian
> 
> In brownian_interval.py, edit line 31 from
> 
> ```
> generator = torch.Generator(device).manual_seed(int(seed))
> ```
> 
> to
> 
> ```
> generator = torch.Generator().manual_seed(int(seed))
> ```
> 
> ComfyUI should now generate correctly.

Not sure why, but my install of ComfyUI doesn't have the torchsde_brownian folder. Instead it has torchsde\_brownian where I found the same file. However, when I make this edit as suggested, it makes no difference and I get the same error message.

**Comment by aelfwyne** [comment]
For some reason, when I make the same edit on line 31 of the brownian_interval.py, it does not solve this issue. I still get the same error as before.
