### ISSUE TITLE
Several custom_nodes not loading, after last update: 9a151b7

### ISSUE THREAD

**Issue by Pauweltje** [comfyanonymous/ComfyUI#3585]
After the update there are several custom_nodes that are not working anymore, see below:

![image](https://github.com/comfyanonymous/ComfyUI/assets/2523468/92cba465-45a5-44d8-9fd3-d6979638e83d)

Please will there be a fix soon?

If not, how to revert to the earlier version of ComfyUI?

Thanks!

**Comment by ethanfel** [comment]
git checkout ffc4b7c and we have to wait for the customs node to be fixed

**Comment by comfyanonymous** [comment]
https://github.com/comfyanonymous/ComfyUI/commit/16a493a19042227baadd939fc095305716ae58db

This should fix it.

**Comment by Johnz86** [comment]
This resolved my issues. previously some of the nodes failed with:
```
ImportError: cannot import name 'model_loading' from 'comfy_extras.chainner_models
```
Now they successfully started :) 

Thanks

**Comment by KINGLIFER** [comment]
zgenmedia made an awesome post about this. https://www.reddit.com/r/comfyui/comments/1d17r3f/who_else_is_doing_comics_in_the_ai_workspace_not/

**Comment by GalaxyTimeMachine** [comment]
> [16a493a](https://github.com/comfyanonymous/ComfyUI/commit/16a493a19042227baadd939fc095305716ae58db)
> 
> This should fix it.

After this update, I still see errors with the inpaint nodes:

```
### Loading: ComfyUI-Impact-Pack (V5.5.11)
Traceback (most recent call last):
  File "F:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1879, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-inpaint-nodes\__init__.py", line 21, in <module>
    from . import nodes
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-inpaint-nodes\nodes.py", line 14, in <module>
    from comfy_extras.chainner_models.types import PyTorchModel
ModuleNotFoundError: No module named 'comfy_extras.chainner_models.types'
```

**Comment by madriss-mojo** [comment]
Weirdly the Upscale Image (using Model) node doesn't work

**Comment by aniketgore** [comment]
Even after checking out to ffc4b7c30e35eb2773ace52a0b00e0ca5c1f4362 still getting  0.0 seconds (IMPORT FAILED): /SD/comfy/ComfyUI/custom_nodes/comfyui-inpaint-nodes

**Comment by Ainaemaet** [comment]
> I solved the problem. Run `update_comfyui_and_python_dependencies.bat` in `ComfyUI\update.`

I have  no 'ComfyUI\update' directory, and there is none in the repo - I'm confused?

**Comment by GalaxyTimeMachine** [comment]
> > I solved the problem. Run `update_comfyui_and_python_dependencies.bat` in `ComfyUI\update.`
> 
> I have no 'ComfyUI\update' directory, and there is none in the repo - I'm confused?

You're probably not using the "portable" version, in which case you'd have to do a "git pull".
