### ISSUE TITLE
Group node feature failing.

### ISSUE THREAD

**Issue by Aenon1** [comfyanonymous/ComfyUI#5052]
### Expected Behavior

You save multiple nodes as a single grouped node in a workflow.

### Actual Behavior

![{10CDDC46-74D9-49F4-88EB-DCECD303C3EF}](https://github.com/user-attachments/assets/966155e0-7cda-45b4-a374-cce5cfd51b8e)

### Steps to Reproduce

Save some nodes to a group in a workflow, close ComfyUI and then reopen it and load the workflow.

### Debug Logs

```powershell
There are no errors in it.
```

### Other

ComfyUI is all of a sudden failing to load created group nodes. Even the ones that I just created today.
I use that feature extensively and today, every workflow I have that contains a group fails. It displays the grouped node as a missing node(turns it red). I'm using base ComfyUI nodes to make them, it is not a problem of a custom node.
Also, you can no longer save a grouped node as a component. I don't know if that is an issue with ComfyUI or Manager. The ability to create a grouped node is ComfyUI though.

**Comment by Aenon1** [comment]
It appears something has been changed in the way Comfy reads/saves grouped nodes.
The 1st image is an older workflow, it actually saved the 'groupdnode' and listed everything in it.
The 2nd image shows a 'groupnode' in a workflow that I just saved, it saved nothing and it can't read the groupnode from the old workflow.
![{FE3D041A-1796-40E2-8186-E7430268830D}](https://github.com/user-attachments/assets/fa98b84e-dad7-4624-980d-ce6c5f9f411e)
![{5A7D1723-7D17-44CF-BF55-DADBE34D0BE1}](https://github.com/user-attachments/assets/9f8f5d49-4b8a-4263-9dac-2acc59bfa238)

**Comment by christian-byrne** [comment]
Comfy-Org/ComfyUI_frontend#950 is conflicting with ComfyUI-Manager.

**Comment by Aenon1** [comment]
Yes. I tried the new front end, and the old one, same. I even tried installing the portable version, same thing. I found 2 instances of 'workflow/Base' in an older workflow and changed it to workflow>Base, that didn't work.

**Comment by christian-byrne** [comment]
Does it work when disabling manager? And can you provide one of the workflows?

**Comment by K-O-N-B** [comment]
I meet another group node problem when update to 89fa2fc:

![image](https://github.com/user-attachments/assets/d6773d18-37cc-4ebf-8586-d9679ade5943)
![image](https://github.com/user-attachments/assets/e3d28b69-8c1f-4d2f-9b7c-b9703c667b3d)

before that:
![image](https://github.com/user-attachments/assets/4b589049-f9e2-4e6c-83e9-0af23ec863bd)

**Comment by christian-byrne** [comment]
> I meet another group node problem when update to [89fa2fc](https://github.com/comfyanonymous/ComfyUI/commit/89fa2fca24cf6f276ae181288df515506eed0d22):
> 
> ![image](https://private-user-images.githubusercontent.com/152141077/370523841-d6773d18-37cc-4ebf-8586-d9679ade5943.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyMjk2OTAsIm5iZiI6MTcyNzIyOTM5MCwicGF0aCI6Ii8xNTIxNDEwNzcvMzcwNTIzODQxLWQ2NzczZDE4LTM3Y2MtNGViZi04NTg2LWQ5Njc5YWRlNTk0My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNVQwMTU2MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNGEwNjIzNzIyZjcxNTVmNzUwNjgzNjM1Y2UyODJmZGNiNDBlMzc0YzAxZDUwNjQ2NmM1MDUwZjllNjdjN2NkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.G6yeB5S2NI9YGd-lUIw2_URke-HxmF4TC-YJ7uJAX4A) ![image](https://private-user-images.githubusercontent.com/152141077/370523932-e3d28b69-8c1f-4d2f-9b7c-b9703c667b3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyMjk2OTAsIm5iZiI6MTcyNzIyOTM5MCwicGF0aCI6Ii8xNTIxNDEwNzcvMzcwNTIzOTMyLWUzZDI4YjY5LThjMWYtNGQyZi05YjdjLWI5NzAzYzY2N2IzZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNVQwMTU2MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYjVmZTE3YmEzYWZhZGUxZDZhY2NhNWE0M2RkY2UwNGViYjE2ZTBmODEwOTUwOGQ1ZTI4MzgyZGE5YjdiZTg5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.12nCDwdYfGzIBMravSEuHWrEtZgm3ti3_RzE3Y5-SI8)
> 
> before that: ![image](https://private-user-images.githubusercontent.com/152141077/370524538-4b589049-f9e2-4e6c-83e9-0af23ec863bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyMjk2OTAsIm5iZiI6MTcyNzIyOTM5MCwicGF0aCI6Ii8xNTIxNDEwNzcvMzcwNTI0NTM4LTRiNTg5MDQ5LWY5ZTItNGU2Yy04M2U5LTBhZjIzZWM4NjNiZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNVQwMTU2MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYThmNDRhNWVjMmQ3MTYyZmRhYWUwNWQ3NjNiZjRiMDk3NjIzYTQzMmZhNTQyYjlkM2M4YzI4NWM4MWI2YWI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.8DdTQaB61ebUheI7PO4sLGM4kkaM1BWe-Cy0DC2QwK4)

That's a separate issue which you can most likely solve by updating mixlab nodes

**Comment by Aenon1** [comment]
> Does it work when disabling manager? And can you provide one of the workflows?

No, it does the same thing. Here is a simple GGUF based workflow that was working great yesterday.
[Flux_GGUF_Simple_G.json](https://github.com/user-attachments/files/17123376/Flux_GGUF_Simple_G.json)

**Comment by christian-byrne** [comment]
For me your workflow works on the stable frontend version. You might have to close and reopen the tab. I belibe the issue is with https://github.com/Comfy-Org/ComfyUI_frontend/pull/950

**Comment by Aenon1** [comment]
> For me your workflow works on the stable frontend version. You might have to close and reopen the tab. I believe the issue is with [Comfy-Org/ComfyUI_frontend#950](https://github.com/Comfy-Org/ComfyUI_frontend/pull/950)

That did it, thank you! I changed my launch bat to load the stable instead of the latest front end:

echo Running the application...
python main.py --front-end-version Comfy-Org/ComfyUI_frontend@stable

I'll mark this as solved, again thanks!

**Comment by christian-byrne** [comment]
@Aenon1 It should be fixed now so you can go back to using `ComfyUI_frontend@latest` if you'd like.

**Comment by Aenon1** [comment]
> @Aenon1 It should be fixed now so you can go back to using `ComfyUI_frontend@latest` if you'd like.

Thank you!

**Comment by Aenon1** [comment]
> @Aenon1 It should be fixed now so you can go back to using `ComfyUI_frontend@latest` if you'd like.

Somebody pushed something and I am back to the group nodes not working again. I put
 --front-end-version Comfy-Org/ComfyUI_frontend@stable
in my launch bat file and that is throwing an error stating: 
Failed to initialize frontend: Invalid version string: Comfy-Org/ComfyUI_frontend@stable
What can I do for this? I tried putting it back to latest and then removed the call completely and the group nodes do not work with either.

**Comment by PrometheusDante** [comment]
This is definitely a thing that still happens for me and users of my workflows, despite all custom node packs being installed, up to date, properly imported and functional.
When I provide a workflow with all group nodes simply broken up into their elements without any changes it loads just fine for everyone.

While working on group nodes I sometimes find weird issues like having group nodes missing(failing to load) upon start, and upon reloading only a few are missing, next restart they might all load. It is highly erratic at the moment and frustrating to work with.

Group nodes are such a fantastic feature, that could really do with a few obvious quality of life updates.

**Comment by Latentnaut** [comment]
It happened to me Today, I've sent a Workflow with Group Nodes inside and they are red to my buddy, and all the Custom Packages are well installed.

**Comment by schoenid** [comment]
It happens also to all of my workflows until March 2025 after **_every_** update of ComfyUI.

Then I've stopped using Group Nodes.

I've edited all my older workflows in VSC and removed all the grouping. Since then I can use them again. 
Pfff, what a work!

**Comment by schoenid** [comment]
I've got also an error message in DevTools of my browser:

![Image](https://github.com/user-attachments/assets/dcd248e9-aa17-43a9-a042-a13a0e084ffa)

I guess, this prevents from loading groups ...
