### ISSUE TITLE
GGUF clip files not shown in workflows

### ISSUE THREAD

**Issue by sugatasanshiro** [comfyanonymous/ComfyUI#5499]
### Expected Behavior

![92FC3f85R0](https://github.com/user-attachments/assets/63b32309-b0ee-40be-87fd-54cffd72311e)

### Actual Behavior

![brave_zlD7arU7fe](https://github.com/user-attachments/assets/a197b754-6775-438b-a206-25be33bc9c52)

### Steps to Reproduce

just update ComfyUI

### Debug Logs

```powershell
nothing
```

**Comment by gtx155** [comment]
Update your gguf extension. There was a fix released

**Comment by sugatasanshiro** [comment]
ok

**Comment by Luisdar0z** [comment]
For some reason it doesn't show me the gguf clips even after updating the gguf extension... I found a workaround and it is to add **'.gguf'** to **line 10** of **folder_paths.py** such that `supported_pt_extensions: set[str] = {'.ckpt', '.pt', '.bin', '.pth', '.safetensors', '.pkl', '.sft', '.gguf'}` and then it shows me the gguf clips... I don't know how or why but it works for me.

**Comment by sugatasanshiro** [comment]
after updating the GGUF extension - it works

**Comment by 4drawing95** [comment]
I updated ComfyUI and the gguf custom nodes to the latest versions, but this issue still hasn't been resolved. The solution is to search for **folder_paths.py** in the **ComfyUI directory, find it, and add '.gguf' to the 10th line.**
