### ISSUE TITLE
ERROR lora diffusion_model.img_in.weight shape '[3072, 64]' is invalid for input of size 393216

### ISSUE THREAD

**Issue by guangquanshao** [comfyanonymous/ComfyUI#5868]
### Expected Behavior

I just add the flux1-canny-dev-lora to the workflow.
![微信图片_20241202181606](https://github.com/user-attachments/assets/bb8b0239-54f4-4a74-b5d5-fa83b1a5fe94)

### Actual Behavior

![微信图片_20241202192558](https://github.com/user-attachments/assets/d53989f0-f5af-4409-adcc-e9bd31b1cc5b)

### Steps to Reproduce

[test.json](https://github.com/user-attachments/files/17977205/test.json)

### Debug Logs

```powershell
Using xformers attention in VAE
Using xformers attention in VAE
Requested to load FluxClipModel_
Loading 1 new model
loaded completely 0.0 4777.53759765625 True
clip missing: ['text_projection.weight']
Requested to load AutoencodingEngine
Loading 1 new model
loaded completely 0.0 159.87335777282715 True
model weight dtype torch.float8_e4m3fn, manual cast: torch.bfloat16
model_type FLUX
Requested to load Flux
Loading 1 new model
ERROR lora diffusion_model.img_in.weight shape '[3072, 64]' is invalid for input of size 393216
patch type not recognized set diffusion_model.single_blocks.9.norm.query_norm.scale
patch type not recognized set diffusion_model.single_blocks.9.norm.key_norm.scale
patch type not recognized set diffusion_model.single_blocks.8.norm.query_norm.scale
patch type not recognized set diffusion_model.single_blocks.8.norm.key_norm.scale
patch type not recognized set diffusion_model.single_blocks.7.norm.query_norm.scale
patch type not recognized set diffusion_model.single_blocks.7.norm.key_norm.scale
patch type not recognized set diffusion_model.single_blocks.6.norm.query_norm.scale
patch type not recognized set diffusion_model.single_blocks.6.norm.key_norm.scale
patch type not recognized set diffusion_model.single_blocks.5.norm.query_norm.scale
patch type not recognized set diffusion_model.single_blocks.5.norm.key_norm.scale
patch type not recognized set diffusion_model.single_blocks.4.norm.query_norm.scale
patch type not recognized set diffusion_model.single_blocks.4.norm.key_norm.scale
patch type not recognized set diffusion_model.single_blocks.37.norm.query_norm.scale
patch type not recognized set diffusion_model.single_blocks.37.norm.key_norm.scale
patch type not recognized set diffusion_model.single_blocks.36.norm.query_norm.scale
patch type not recognized set diffusion_model.single_blocks.36.norm.key_norm.scale
patch type not recognized set diffusion_model.single_blocks.35.norm.query_norm.scale
patch type not recognized set diffusion_model.single_blocks.35.norm.key_norm.scale
patch type not recognized set diffusion_model.single_blocks.34.norm.query_norm.scale
patch type not recognized set diffusion_model.single_blocks.34.norm.key_norm.scale
patch type not recognized set diffusion_model.single_blocks.33.norm.query_norm.scale
patch type not recognized set diffusion_model.single_blocks.33.norm.key_norm.scale
patch type not recognized set diffusion_model.single_blocks.32.norm.query_norm.scale
patch type not recognized set diffusion_model.single_blocks.32.norm.key_norm.scale
patch type not recognized set diffusion_model.single_blocks.31.norm.query_norm.scale
patch type not recognized set diffusion_model.single_blocks.31.norm.key_norm.scale
patch type not recognized set diffusion_model.single_blocks.30.norm.query_norm.scale
patch type not recognized set diffusion_model.single_blocks.30.norm.key_norm.scale
patch type not recognized set diffusion_model.single_blocks.3.norm.query_norm.scale
patch type not recognized set diffusion_model.single_blocks.3.norm.key_norm.scale
patch type not recognized set diffusion_model.single_blocks.29.norm.query_norm.scale
patch type not recognized set diffusion_model.single_blocks.29.norm.key_norm.scale
patch type not recognized set diffusion_model.single_blocks.28.norm.query_norm.scale
patch type not recognized set diffusion_model.single_blocks.28.norm.key_norm.scale
patch type not recognized set diffusion_model.single_blocks.27.norm.query_norm.scale
patch type not recognized set diffusion_model.single_blocks.27.norm.key_norm.scale
patch type not recognized set diffusion_model.single_blocks.26.norm.query_norm.scale
patch type not recognized set diffusion_model.single_blocks.26.norm.key_norm.scale
patch type not recognized set diffusion_model.single_blocks.25.norm.query_norm.scale
patch type not recognized set diffusion_model.single_blocks.25.norm.key_norm.scale
patch type not recognized set diffusion_model.single_blocks.24.norm.query_norm.scale
patch type not recognized set diffusion_model.single_blocks.24.norm.key_norm.scale
patch type not recognized set diffusion_model.single_blocks.23.norm.query_norm.scale
patch type not recognized set diffusion_model.single_blocks.23.norm.key_norm.scale
patch type not recognized set diffusion_model.single_blocks.22.norm.query_norm.scale
patch type not recognized set diffusion_model.single_blocks.22.norm.key_norm.scale
patch type not recognized set diffusion_model.single_blocks.21.norm.query_norm.scale
patch type not recognized set diffusion_model.single_blocks.21.norm.key_norm.scale
patch type not recognized set diffusion_model.single_blocks.20.norm.query_norm.scale
patch type not recognized set diffusion_model.single_blocks.20.norm.key_norm.scale
patch type not recognized set diffusion_model.single_blocks.2.norm.query_norm.scale
patch type not recognized set diffusion_model.single_blocks.2.norm.key_norm.scale
patch type not recognized set diffusion_model.single_blocks.19.norm.query_norm.scale
patch type not recognized set diffusion_model.single_blocks.19.norm.key_norm.scale
patch type not recognized set diffusion_model.single_blocks.18.norm.query_norm.scale
patch type not recognized set diffusion_model.single_blocks.18.norm.key_norm.scale
patch type not recognized set diffusion_model.single_blocks.17.norm.query_norm.scale
patch type not recognized set diffusion_model.single_blocks.17.norm.key_norm.scale
patch type not recognized set diffusion_model.single_blocks.16.norm.query_norm.scale
patch type not recognized set diffusion_model.single_blocks.16.norm.key_norm.scale
patch type not recognized set diffusion_model.single_blocks.15.norm.query_norm.scale
patch type not recognized set diffusion_model.single_blocks.15.norm.key_norm.scale
patch type not recognized set diffusion_model.single_blocks.14.norm.query_norm.scale
patch type not recognized set diffusion_model.single_blocks.14.norm.key_norm.scale
patch type not recognized set diffusion_model.single_blocks.13.norm.query_norm.scale
patch type not recognized set diffusion_model.single_blocks.13.norm.key_norm.scale
patch type not recognized set diffusion_model.single_blocks.12.norm.query_norm.scale
patch type not recognized set diffusion_model.single_blocks.12.norm.key_norm.scale
patch type not recognized set diffusion_model.single_blocks.11.norm.query_norm.scale
patch type not recognized set diffusion_model.single_blocks.11.norm.key_norm.scale
patch type not recognized set diffusion_model.single_blocks.10.norm.query_norm.scale
patch type not recognized set diffusion_model.single_blocks.10.norm.key_norm.scale
patch type not recognized set diffusion_model.single_blocks.1.norm.query_norm.scale
patch type not recognized set diffusion_model.single_blocks.1.norm.key_norm.scale
patch type not recognized set diffusion_model.single_blocks.0.norm.query_norm.scale
patch type not recognized set diffusion_model.single_blocks.0.norm.key_norm.scale
patch type not recognized set diffusion_model.double_blocks.9.txt_attn.norm.query_norm.scale
patch type not recognized set diffusion_model.double_blocks.9.txt_attn.norm.key_norm.scale
patch type not recognized set diffusion_model.double_blocks.9.img_attn.norm.query_norm.scale
patch type not recognized set diffusion_model.double_blocks.9.img_attn.norm.key_norm.scale
patch type not recognized set diffusion_model.double_blocks.8.txt_attn.norm.query_norm.scale
patch type not recognized set diffusion_model.double_blocks.8.txt_attn.norm.key_norm.scale
patch type not recognized set diffusion_model.double_blocks.8.img_attn.norm.query_norm.scale
patch type not recognized set diffusion_model.double_blocks.8.img_attn.norm.key_norm.scale
patch type not recognized set diffusion_model.double_blocks.7.txt_attn.norm.query_norm.scale
patch type not recognized set diffusion_model.double_blocks.7.txt_attn.norm.key_norm.scale
patch type not recognized set diffusion_model.double_blocks.7.img_attn.norm.query_norm.scale
patch type not recognized set diffusion_model.double_blocks.7.img_attn.norm.key_norm.scale
patch type not recognized set diffusion_model.double_blocks.6.txt_attn.norm.query_norm.scale
patch type not recognized set diffusion_model.double_blocks.6.txt_attn.norm.key_norm.scale
patch type not recognized set diffusion_model.double_blocks.6.img_attn.norm.query_norm.scale
patch type not recognized set diffusion_model.double_blocks.6.img_attn.norm.key_norm.scale
patch type not recognized set diffusion_model.double_blocks.5.txt_attn.norm.query_norm.scale
patch type not recognized set diffusion_model.double_blocks.5.txt_attn.norm.key_norm.scale
patch type not recognized set diffusion_model.double_blocks.5.img_attn.norm.query_norm.scale
patch type not recognized set diffusion_model.double_blocks.5.img_attn.norm.key_norm.scale
patch type not recognized set diffusion_model.double_blocks.4.txt_attn.norm.query_norm.scale
patch type not recognized set diffusion_model.double_blocks.4.txt_attn.norm.key_norm.scale
patch type not recognized set diffusion_model.double_blocks.4.img_attn.norm.query_norm.scale
patch type not recognized set diffusion_model.double_blocks.4.img_attn.norm.key_norm.scale
patch type not recognized set diffusion_model.double_blocks.3.txt_attn.norm.query_norm.scale
patch type not recognized set diffusion_model.double_blocks.3.txt_attn.norm.key_norm.scale
patch type not recognized set diffusion_model.double_blocks.3.img_attn.norm.query_norm.scale
patch type not recognized set diffusion_model.double_blocks.3.img_attn.norm.key_norm.scale
patch type not recognized set diffusion_model.double_blocks.2.txt_attn.norm.query_norm.scale
patch type not recognized set diffusion_model.double_blocks.2.txt_attn.norm.key_norm.scale
patch type not recognized set diffusion_model.double_blocks.2.img_attn.norm.query_norm.scale
patch type not recognized set diffusion_model.double_blocks.2.img_attn.norm.key_norm.scale
patch type not recognized set diffusion_model.double_blocks.18.txt_attn.norm.query_norm.scale
patch type not recognized set diffusion_model.double_blocks.18.txt_attn.norm.key_norm.scale
patch type not recognized set diffusion_model.double_blocks.18.img_attn.norm.query_norm.scale
patch type not recognized set diffusion_model.double_blocks.18.img_attn.norm.key_norm.scale
patch type not recognized set diffusion_model.double_blocks.17.txt_attn.norm.query_norm.scale
patch type not recognized set diffusion_model.double_blocks.17.txt_attn.norm.key_norm.scale
patch type not recognized set diffusion_model.double_blocks.17.img_attn.norm.query_norm.scale
patch type not recognized set diffusion_model.double_blocks.17.img_attn.norm.key_norm.scale
patch type not recognized set diffusion_model.double_blocks.16.txt_attn.norm.query_norm.scale
patch type not recognized set diffusion_model.double_blocks.16.txt_attn.norm.key_norm.scale
patch type not recognized set diffusion_model.double_blocks.16.img_attn.norm.query_norm.scale
patch type not recognized set diffusion_model.double_blocks.16.img_attn.norm.key_norm.scale
patch type not recognized set diffusion_model.double_blocks.15.txt_attn.norm.query_norm.scale
patch type not recognized set diffusion_model.double_blocks.15.txt_attn.norm.key_norm.scale
patch type not recognized set diffusion_model.double_blocks.15.img_attn.norm.query_norm.scale
patch type not recognized set diffusion_model.double_blocks.15.img_attn.norm.key_norm.scale
patch type not recognized set diffusion_model.double_blocks.14.txt_attn.norm.query_norm.scale
patch type not recognized set diffusion_model.double_blocks.14.txt_attn.norm.key_norm.scale
patch type not recognized set diffusion_model.double_blocks.14.img_attn.norm.query_norm.scale
patch type not recognized set diffusion_model.double_blocks.14.img_attn.norm.key_norm.scale
patch type not recognized set diffusion_model.double_blocks.13.txt_attn.norm.query_norm.scale
patch type not recognized set diffusion_model.double_blocks.13.txt_attn.norm.key_norm.scale
patch type not recognized set diffusion_model.double_blocks.13.img_attn.norm.query_norm.scale
patch type not recognized set diffusion_model.double_blocks.13.img_attn.norm.key_norm.scale
patch type not recognized set diffusion_model.double_blocks.12.txt_attn.norm.query_norm.scale
patch type not recognized set diffusion_model.double_blocks.12.txt_attn.norm.key_norm.scale
patch type not recognized set diffusion_model.double_blocks.12.img_attn.norm.query_norm.scale
patch type not recognized set diffusion_model.double_blocks.12.img_attn.norm.key_norm.scale
patch type not recognized set diffusion_model.double_blocks.11.txt_attn.norm.query_norm.scale
patch type not recognized set diffusion_model.double_blocks.11.txt_attn.norm.key_norm.scale
patch type not recognized set diffusion_model.double_blocks.11.img_attn.norm.query_norm.scale
patch type not recognized set diffusion_model.double_blocks.11.img_attn.norm.key_norm.scale
patch type not recognized set diffusion_model.double_blocks.10.txt_attn.norm.query_norm.scale
patch type not recognized set diffusion_model.double_blocks.10.txt_attn.norm.key_norm.scale
patch type not recognized set diffusion_model.double_blocks.10.img_attn.norm.query_norm.scale
patch type not recognized set diffusion_model.double_blocks.10.img_attn.norm.key_norm.scale
patch type not recognized set diffusion_model.double_blocks.1.txt_attn.norm.query_norm.scale
patch type not recognized set diffusion_model.double_blocks.1.txt_attn.norm.key_norm.scale
patch type not recognized set diffusion_model.double_blocks.1.img_attn.norm.query_norm.scale
patch type not recognized set diffusion_model.double_blocks.1.img_attn.norm.key_norm.scale
patch type not recognized set diffusion_model.double_blocks.0.txt_attn.norm.query_norm.scale
patch type not recognized set diffusion_model.double_blocks.0.txt_attn.norm.key_norm.scale
patch type not recognized set diffusion_model.double_blocks.0.img_attn.norm.query_norm.scale
patch type not recognized set diffusion_model.double_blocks.0.img_attn.norm.key_norm.scale
loaded partially 10969.959919891358 10968.944396972656 84
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [03:31<00:00, 10.59s/it]
Requested to load AutoencodingEngine
Loading 1 new model
loaded completely 0.0 159.87335777282715 True
Prompt executed in 310.07 seconds
```

**Comment by ltdrdata** [comment]
Make sure your ComfyUI is up to date.

**Comment by come880412** [comment]
I've updated my ComfyUI to the latest version, but I still got the same issue.

**Comment by AndrewDrimer** [comment]
Same error

**Comment by ltdrdata** [comment]
> @ltdrdata I've updated my ComfyUI to the latest version, but I still got the same issue.

What is your ComfyUI version?
![image](https://github.com/user-attachments/assets/8fe58294-75ba-417d-9e9f-8f43a26373e2)

**Comment by come880412** [comment]
@ltdrdata 
I downloaded the repository from the v0.3.6 release, but I’m not sure why the ComfyUI interface shows an unknown version.

![螢幕擷取畫面 2024-12-12 112943](https://github.com/user-attachments/assets/f4f52140-c583-4a68-8f9b-0cf2a23f532e)

**Comment by ltdrdata** [comment]
> @ltdrdata I downloaded the repository from the v0.3.6 release, but I’m not sure why the ComfyUI interface shows an unknown version.
> 
> ![螢幕擷取畫面 2024-12-12 112943](https://private-user-images.githubusercontent.com/59093784/394997593-f4f52140-c583-4a68-8f9b-0cf2a23f532e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5NzcwMDUsIm5iZiI6MTczMzk3NjcwNSwicGF0aCI6Ii81OTA5Mzc4NC8zOTQ5OTc1OTMtZjRmNTIxNDAtYzU4My00YTY4LThmOWItMGNmMmEyM2Y1MzJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEyVDA0MTE0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyNTY5NWVmOGJmZDU3NDk4MmJjY2JjZTQ0NmVmMzk1MTMwNTgxZTI0YzNiNGRmOTQxMjk3ZDBkYmE4YjA0NTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4jJSyNseph-WFvme0mKnFW10J5DB65TYX5hg6FiQx2o)

How did you install the ComfyUI?

**Comment by lipeng1109** [comment]
me too

ERROR lora diffusion_model.img_in.weight shape '[3072, 384]' is invalid for input of size 196608

**Comment by executorrr86** [comment]
same error

**Comment by JissiChoi** [comment]
I got same error 
"ERROR lora diffusion_model.img_in.weight shape '[3072, 64]' is invalid for input of size 393216"
from the first day until today... when using canny-lora or depth-lora models.

I tried to delete some custom nodes unused recently.
- ComfyUI-Vextra-Nodes
- comfyui-tensorop
- ComfyUI Fooocus Nodes
- ComfyUI_MiniCPM-V-2_6-int4

Then the error is fixed. ^^;
Try this!!! Good luck!!!

**Comment by lipeng1109** [comment]
An error occurs when using hyper to accelerate flux：ERROR lora diffusion_model.img_in.weight shape '[3072, 384]' is invalid for input of size 196608

I mistakenly used the flux dev acceleration lora to the flux fill dev model.

**Comment by kanarch66** [comment]
got this error too.  I use flux 1 dev alpha lora to reduce steps with the normal flux 1 dev fp8 model

ERROR lora diffusion_model.img_in.weight shape '[3072, 128]' is invalid for input of size 196608

**Comment by ltdrdata** [comment]
This issue can occur when using an outdated version of ComfyUI, and in some cases, certain custom nodes may override parts of ComfyUI's functionality with outdated code, causing issues.

If the same issue occurs even with all custom nodes disabled in the latest version of ComfyUI, please reopen the issue.

**Comment by ktee95** [comment]
> got this error too. I use flux 1 dev alpha lora to reduce steps with the normal flux 1 dev fp8 model. I also use the flux 1 dev depth lora in the workflow.
> 
> ERROR lora diffusion_model.img_in.weight shape '[3072, 128]' is invalid for input of size 196608
> 
> image is still generating but it is very slow

same here. i got ERROR lora diffusion_model.img_in.weight shape '[3072, 384]' is invalid for input of size 196608 
when try to use Turbo alpha lora . tried to remove ComfyUI-Vextra-Nodes but error still there.

**Comment by iopsych1975** [comment]
I have updated Comfy, deleted nodes, and still get the same ERROR lora diffusion_model.img_in.weight shape '[3072, 384]' is invalid for input of size 196608.

Has anyone found a solution?

**Comment by ltdrdata** [comment]
![Image](https://github.com/user-attachments/assets/27d75630-1ef2-4af1-b751-944aa3bbc9db)

Anyone experiencing this issue should first check the ComfyUI version on the About page and then upload the exact workflow. (It's not just about the structure; details such as the configured model also need to be verified.)

**Comment by alexgilseg** [comment]
I'm having the same issue with the controlnet depth lora.. otherwise everythings works fine... but I'm getting the same error as above. I've installed a fresh version of comfy etc.. nothing seem to work.. any thoughts ?
