### ISSUE TITLE
KSampler Unsupported head_dim: 160 with SD1.5 and --use-sage-attention

### ISSUE THREAD

**Issue by geroldmeisinger** [comfyanonymous/ComfyUI#7352]
### Expected Behavior

* fallback to simple attention mechanism (but this may be undesirable when I want to force sageattention, so there should be some warning "sage attention not installed/supported, falling back to default attention mechanism")

* this may depend on the semantics of the attention parameters, but
is ` --use-sage-attention` meant to be "use sage attention as PREFERRED attention mechanism" or "FORCE sage attention and fail otherwise"? but there are other parameters named `--disable-xyz` and some `--force-xyz` and the semantics may be inconsistent.

```
$ python main.py --help

  --use-split-cross-attention
                        Use the split cross attention optimization. Ignored
                        when xformers is used.
  --use-quad-cross-attention
                        Use the sub-quadratic cross attention optimization .
                        Ignored when xformers is used.
  --use-pytorch-cross-attention
                        Use the new pytorch 2.0 cross attention function.
  --use-sage-attention  Use sage attention.
  --use-flash-attention
                        Use FlashAttention.
  --disable-xformers    Disable xformers.
  --force-upcast-attention
                        Force enable attention upcasting, please report if it
                        fixes black images.
  --dont-upcast-attention
                        Disable all upcasting of attention. Should be
                        unnecessary except for debugging.
```

* state in the error message that sage attention is not supported for SD1.5

* otherwise, how can I use sage attention on SDXL and non-sageattention on SD1.5 in the same ComfyUI session?

### Actual Behavior

![Image](https://github.com/user-attachments/assets/2fdeb544-b9a1-472e-b26e-9a3c5e3180e8)

### Steps to Reproduce

1. start with `python main.py --use-sage-attention`
2. run the default txt2img workflow with Stable Diffusion 1.5

### Debug Logs

(btw I also tried with `--disable-all-custom-nodes`, it's the same)

```powershell
# ComfyUI Error Report
## Error Details
- **Node ID:** 3
- **Node Type:** KSampler
- **Exception Type:** ValueError
- **Exception Message:** Unsupported head_dim: 160
## Stack Trace

  File "~/ComfyUI/execution.py", line 327, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/execution.py", line 202, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)

  File "~/ComfyUI/execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/nodes.py", line 1543, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/nodes.py", line 1510, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/comfy/sample.py", line 45, in sample
    samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/custom_nodes/ComfyUI-TiledDiffusion/utils.py", line 51, in KSampler_sample
    return orig_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/comfy/samplers.py", line 1133, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/comfy/samplers.py", line 1023, in sample
    return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/comfy/samplers.py", line 1008, in sample
    output = executor.execute(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/comfy/patcher_extension.py", line 110, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/comfy/samplers.py", line 976, in outer_sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/comfy/samplers.py", line 959, in inner_sample
    samples = executor.execute(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/comfy/patcher_extension.py", line 110, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/custom_nodes/ComfyUI-TiledDiffusion/utils.py", line 34, in KSAMPLER_sample
    return orig_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/comfy/samplers.py", line 738, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/venv/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/comfy/k_diffusion/sampling.py", line 161, in sample_euler
    denoised = model(x, sigma_hat * s_in, **extra_args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/comfy/samplers.py", line 390, in __call__
    out = self.inner_model(x, sigma, model_options=model_options, seed=seed)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/comfy/samplers.py", line 939, in __call__
    return self.predict_noise(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/comfy/samplers.py", line 942, in predict_noise
    return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/comfy/samplers.py", line 370, in sampling_function
    out = calc_cond_batch(model, conds, x, timestep, model_options)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/comfy/samplers.py", line 206, in calc_cond_batch
    return executor.execute(model, conds, x_in, timestep, model_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/comfy/patcher_extension.py", line 110, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/comfy/samplers.py", line 319, in _calc_cond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/comfy/model_base.py", line 133, in apply_model
    return comfy.patcher_extension.WrapperExecutor.new_class_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/comfy/patcher_extension.py", line 110, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/comfy/model_base.py", line 165, in _apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/comfy/ldm/modules/diffusionmodules/openaimodel.py", line 831, in forward
    return comfy.patcher_extension.WrapperExecutor.new_class_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/comfy/patcher_extension.py", line 110, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/comfy/ldm/modules/diffusionmodules/openaimodel.py", line 873, in _forward
    h = forward_timestep_embed(module, h, emb, context, transformer_options, time_context=time_context, num_video_frames=num_video_frames, image_only_indicator=image_only_indicator)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/comfy/ldm/modules/diffusionmodules/openaimodel.py", line 44, in forward_timestep_embed
    x = layer(x, context, transformer_options)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/comfy/ldm/modules/attention.py", line 849, in forward
    x = block(x, context=context[i], transformer_options=transformer_options)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/comfy/ldm/modules/attention.py", line 736, in forward
    n = self.attn1(n, context=context_attn1, value=value_attn1)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/comfy/ldm/modules/attention.py", line 630, in forward
    out = optimized_attention(q, k, v, self.heads, attn_precision=self.attn_precision)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/comfy/ldm/modules/attention.py", line 492, in attention_sage
    out = sageattn(q, k, v, attn_mask=mask, is_causal=False, tensor_layout=tensor_layout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/SageAttention/sageattention/core.py", line 132, in sageattn
    return sageattn_qk_int8_pv_fp8_cuda(q, k, v, tensor_layout=tensor_layout, is_causal=is_causal, sm_scale=sm_scale, return_lse=return_lse, pv_accum_dtype="fp32+fp32")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/venv/lib/python3.11/site-packages/torch/_dynamo/eval_frame.py", line 745, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/SageAttention/sageattention/core.py", line 697, in sageattn_qk_int8_pv_fp8_cuda
    raise ValueError(f"Unsupported head_dim: {head_dim_og}")


## System Information
- **ComfyUI Version:** 0.3.26
- **Arguments:** main.py --use-sage-attention
- **OS:** posix
- **Python Version:** 3.11.2 (main, Nov 30 2024, 21:22:50) [GCC 12.2.0]
- **Embedded Python:** false
- **PyTorch Version:** 2.6.0+cu124
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 4060 Ti : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 16848846848
  - **VRAM Free:** 12505243444
  - **Torch VRAM Total:** 2013265920
  - **Torch VRAM Free:** 13360948
```

### Other

related:
https://github.com/comfyanonymous/ComfyUI/issues/6733
https://github.com/thu-ml/SageAttention/issues/119

my sage attention installation works for SDXL, Flux and Wan

**Comment by comfyanonymous** [comment]
Should be fixed now.

**Comment by geroldmeisinger** [comment]
@comfyanonymous 
console spam:
```
Error running sage attention: headdim should be in [64, 96, 128]., using pytorch attention instead.
Error running sage attention: headdim should be in [64, 96, 128]., using pytorch attention instead.
Error running sage attention: headdim should be in [64, 96, 128]., using pytorch attention instead.
Error running sage attention: headdim should be in [64, 96, 128]., using pytorch attention instead.
Error running sage attention: headdim should be in [64, 96, 128]., using pytorch attention instead.
Error running sage attention: headdim should be in [64, 96, 128]., using pytorch attention instead.
Error running sage attention: headdim should be in [64, 96, 128]., using pytorch attention instead.
Error running sage attention: headdim should be in [64, 96, 128]., using pytorch attention instead.
Error running sage attention: headdim should be in [64, 96, 128]., using pytorch attention instead.
Error running sage attention: headdim should be in [64, 96, 128]., using pytorch attention instead.
Error running sage attention: headdim should be in [64, 96, 128]., using pytorch attention instead.
Error running sage attention: headdim should be in [64, 96, 128]., using pytorch attention instead.
Error running sage attention: headdim should be in [64, 96, 128]., using pytorch attention instead.
Error running sage attention: headdim should be in [64, 96, 128]., using pytorch attention instead.
Error running sage attention: headdim should be in [64, 96, 128]., using pytorch attention instead.
Error running sage attention: headdim should be in [64, 96, 128]., using pytorch attention instead.
Error running sage attention: headdim should be in [64, 96, 128]., using pytorch attention instead.
Error running sage attention: headdim should be in [64, 96, 128]., using pytorch attention instead.
Error running sage attention: headdim should be in [64, 96, 128]., using pytorch attention instead.
Error running sage attention: headdim should be in [64, 96, 128]., using pytorch attention instead.
Error running sage attention: headdim should be in [64, 96, 128]., using pytorch attention instead.
Error running sage attention: headdim should be in [64, 96, 128]., using pytorch attention instead.
Error running sage attention: headdim should be in [64, 96, 128]., using pytorch attention instead.
Error running sage attention: headdim should be in [64, 96, 128]., using pytorch attention instead.
Error running sage attention: headdim should be in [64, 96, 128]., using pytorch attention instead.
Error running sage attention: headdim should be in [64, 96, 128]., using pytorch attention instead.
Error running sage attention: headdim should be in [64, 96, 128]., using pytorch attention instead.
Error running sage attention: headdim should be in [64, 96, 128]., using pytorch attention instead.
Error running sage attention: headdim should be in [64, 96, 128]., using pytorch attention instead.
Error running sage attention: headdim should be in [64, 96, 128]., using pytorch attention instead.
Error running sage attention: headdim should be in [64, 96, 128]., using pytorch attention instead.
Error running sage attention: headdim should be in [64, 96, 128]., using pytorch attention instead.
```

**Comment by jkrauss82** [comment]
I had the same issue and can confirm @comfyanonymous's fix is working (sage attention 2.1.1)

to get rid of the logging I have commented [this line](https://github.com/comfyanonymous/ComfyUI/blob/master/comfy/ldm/modules/attention.py#L495) for now

**Comment by joeluo** [comment]
I found the issue still exist.
comfyUI v0.3.27 does not include the @comfyanonymous's fix, you must git checkout master, but even modified attention.py, the issue still exist.
If add ComfyUI\main.py --use-sage-attention , and use sd1.5 checkpoint, ksampler will stop working, show the error message 'Unsupported head_dim: 160'.

**Comment by AugmentedRealityCat** [comment]
Looks like I have a very similar problem. Here is the error message:
```
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\sageattention\core.py", line 82, in sageattn
    assert headdim in [64, 96, 128], "headdim should be in [64, 96, 128]."
           ^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: headdim should be in [64, 96, 128].
```
Should I revert back to an older version of ComfyUI to fix this ?

**Comment by geroldmeisinger** [comment]
works for me in 0.3.27. are you sure you are on the right version/checkout?

**Comment by AugmentedRealityCat** [comment]
I am also using 0.3.27.
```
ComfyUI version: 0.3.27
ComfyUI frontend version: 1.14.6
```
My problem is slightly different though: I am not using the --use-sage-attention tag and this error also happens with Flux.

There is also a mention here:
https://github.com/comfyanonymous/ComfyUI/issues/6733

As for my own problem I first thought it  was related to a new custom node I had installed so I posted it on that repo instead:
https://github.com/Stable-X/ComfyUI-Hi3DGen/issues/4#issuecomment-2781054851

This link above had a complete log + workflow as exported from ComfyUI for error reporting.

**Comment by PhoenixGameDevelopment** [comment]
I am also getting this issue on the latest (3.27) version of ComfyUI using a very simple workflow.

**Comment by AugmentedRealityCat** [comment]
Remove ComfyUI-Hi3DGen from your custom nodes and that should fix the problem.

**Comment by PhoenixGameDevelopment** [comment]
I don't have that node? I am just using a very basic workflow, and the KSamplers if throwing the error. Maybe I installed sage attention wrong?

**Comment by Poukpalaova** [comment]
I'm also in a similar situation. I have --use-sage-attention and that look to work since i'm runing the new flux nunchaku pipline BUT, if i run a simple SDXL/Pony workflow, at the ksampler it becore very slow and i see that in consol:
leftover keys: dict_keys(['down_blocks.1.attentions.0.norm.bias', 'down_blocks.1.attentions.0.norm.weight', 'down_blocks.1.attentions.0.proj_in.bias', 'down_blocks.1.attentions.0.proj_in.weight', 'down_blocks.1.attentions.0.proj_out.bias', 'down_blocks.1.attentions.0.proj_out.weight', 'down_blocks.1.attentions.1.norm.bias', 'down_blocks.1.attentions.1.norm.weight', 'down_blocks.1.attentions.1.proj_in.bias', 'down_blocks.1.attentions.1.proj_in.weight', 'down_blocks.1.attentions.1.proj_out.bias', 'down_blocks.1.attentions.1.proj_out.weight'])
Token indices sequence length is longer than the specified maximum sequence length for this model (94 > 77). Running this sequence through the model will result in indexing errors
Token indices sequence length is longer than the specified maximum sequence length for this model (94 > 77). Running this sequence through the model will result in indexing errors
Requested to load SDXL
Requested to load ControlNet
loaded completely 6479.8428218841555 4897.0483474731445 True
loaded partially 128.0 127.99920654296875 0
  0%|                                                                                           | 0/15 [00:00<?, ?it/s]
Error running sage attention: [WinError 2] Le fichier spécifié est introuvable, using pytorch attention instead.
Error running sage attention: [WinError 2] Le fichier spécifié est introuvable, using pytorch attention instead.

And the last line is repeating like 200 times and it take for ever to generate a simple image. (654s)
Is that because I still have another workflow tab open with that nunchaku pipline in it?

**Comment by merc4derp** [comment]
There seems to be a bug here.

I was running a wan workflow with sage attention enabled. Then switched to a flux/sd15 workflow without sage attention and this error popped up.
Restarted the server and the flux/sd15 workflow worked again.

Something left over that doesn't get unloaded if you use sage attention and then switch to a workflow without it?

**Comment by hwprinz** [comment]
as all posters above say
- some is working, some not

and nothing is fixed so far until even SD1.5 runs properly incl. sage attention.
it's not only *log-spam*, as people call it.
it does what it says:
*Error running sage attention: Unsupported head_dim: 160, using pytorch attention instead.*
in other words, yes, it still works, but using pytorch instead of sage

Even today, quite actual install:
```
pytorch version: 2.7.0+cu128
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4060 Ti : cudaMallocAsync
Using sage attention
Python version: 3.12.9 (tags/v3.12.9:fdb8142, Feb  4 2025, 15:27:58) [MSC v.1942 64 bit (AMD64)]
ComfyUI version: 0.3.33
ComfyUI frontend version: 1.18.9
### Loading: ComfyUI-Manager (V3.31.13)
[ComfyUI-Manager] network_mode: public
### ComfyUI Version: v0.3.33-7-gd4261368 | Released on '2025-05-10'
```
also in another Installation some older
also in some most actual, even Nightly installs
as like pytorch version: 2.8.0+cu128

btw.
**tritron-windows 3.3.0
sage-attention 2.1.1**

also noticed as above, depending on how you change to different models back and forth
might require a restart Comfy Sytsem to get back running in models which usually work..
Would be great to get some progress

**Comment by Sunnerick** [comment]
Kj recomdations:   Run SageAttention  patch , this time disabled to offload it

**Comment by hwprinz** [comment]
that is correct.
i meanwhile start ComfyUI with --use-flash-attention
but using Kijai's patch nodes to explicitly enable sage for any other model based stuff, except SD of course
