### ISSUE TITLE
Loading aborted due to error reloading workflow data TypeError: graph.nodes is not iterable

### ISSUE THREAD

**Issue by pawnzhang** [comfyanonymous/ComfyUI#7645]
I just update comfyUI from 0.3.27 to 0.3.29, start program and show the following info: need help!
Loading aborted due to error reloading workflow data TypeError: graph.nodes is not iterable

![Image](https://github.com/user-attachments/assets/8a2e2b89-c099-4b3b-806b-1915088b51eb)

**Comment by christian-byrne** [comment]
Can open dev console with F12 and show what appears there (full error log)?

**Comment by pawnzhang** [comment]
> Can open dev console with F12 and show what appears there (full error log)?

I can open dev console with F12, 

![Image](https://github.com/user-attachments/assets/23a399bb-0df8-495c-97c3-9d28c1777a27)

and When I open the workflow file, I encounter the graph.nodes error mentioned earlier, but there is no additional error information. The "Show Report" only displays the workflow content:

## Attached Workflow  
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.  
'''
{"id":"1b83bbbc-b6df-453b-b4e2-7bd34aec18ed","revision":0,"last_node_id":0,"last_link_id":0,"nodes":[],"links":[],"groups":[],"config":{},"extra":{"ds":{"scale":1,"offset":[793,160]}},"version":0.4} 
'''
Additional Context
(Please add any additional context or steps to reproduce the error here)

**Comment by pawnzhang** [comment]
It seems compatibility issues between the workflow format and the updated ComfyUI version. I guess

**Comment by christian-byrne** [comment]
Thank you. Actually, by "dev console", I was referring to the browser dev console which you open by pressing the F12 key while the browser is focused (typically).

For this issue though, it seems to be a custom node that's causing the issue, since I cannot reproduce the on my end. 

Can you try launching with `--disable-all-custom-nodes` to confirm the issue is fixed that way? 

If that is confirmed, it would be helpful if you could pinpoint which custom node causes the issue. You can do so by disabling disabling half, then disabling half of remaining, then halving again, repeat (binary search). This way you can probably find the culprit quickly.

Related issue: https://github.com/comfyanonymous/ComfyUI/issues/7630

**Comment by pawnzhang** [comment]
> 谢谢。实际上，我所说的“开发控制台”是指在浏览器聚焦时（通常）通过按 F12 键打开的浏览器开发控制台。
> 
> 但是，对于此问题，似乎是自定义节点导致了问题，因为我无法在我这边重现 。
> 
> 您能否尝试启动以确认问题已以这种方式得到解决？`--disable-all-custom-nodes`
> 
> 如果确认了这一点，那么如果您可以查明导致问题的自定义节点，将会很有帮助。为此，您可以禁用 half，然后禁用 half of remaining，然后再次减半，重复（二叉搜索）。这样你可能会很快找到罪魁祸首。
> 
> 相关问题：[#7630](https://github.com/comfyanonymous/ComfyUI/issues/7630)

I don't think it's a custom node issue, because even when I create a new empty workflow, the system still gets this error.

**Comment by kokomo** [comment]
In my case, the conflict was caused by crystools, crystool save and prompt_gallery.

**Comment by pawnzhang** [comment]
> In my case, the conflict was caused by crystools, crystool save and prompt_gallery.

Yes, I uninstall crytools save and fix the workflow's error, tks.  CryTools_save nodes conflict.

**Comment by pawnzhang** [comment]
> Thank you. Actually, by "dev console", I was referring to the browser dev console which you open by pressing the F12 key while the browser is focused (typically).
> 
> For this issue though, it seems to be a custom node that's causing the issue, since I cannot reproduce the on my end.
> 
> Can you try launching with `--disable-all-custom-nodes` to confirm the issue is fixed that way?
> 
> If that is confirmed, it would be helpful if you could pinpoint which custom node causes the issue. You can do so by disabling disabling half, then disabling half of remaining, then halving again, repeat (binary search). This way you can probably find the culprit quickly.
> 
> Related issue: [#7630](https://github.com/comfyanonymous/ComfyUI/issues/7630)

tks, it caused by crytools_save nodes, tks.

**Comment by christian-byrne** [comment]
Please report the error the crystools repo if you find the time. You can help speed the process of the issue being fixed.

**Comment by pawnzhang** [comment]
> Please report the error the crystools repo if you find the time. You can help speed the process of the issue being fixed.

Tks , The error information I posted earlier is all there is, and I also reported the error in ComfyUI. However, there was no information pointing to Cry Tools Save. When I uninstalled it, the problem was resolved. My understanding is that the ComfyUI frontend upgrade to version 1.16 changed the workflow reading process, and this change conflicted with how Cry Tools Save handles workflow formats, leading to issues with reading all workflows.

**Comment by YoullNeverSee** [comment]
> > Please report the error the crystools repo if you find the time. You can help speed the process of the issue being fixed.
> 
> Tks , The error information I posted earlier is all there is, and I also reported the error in ComfyUI. However, there was no information pointing to Cry Tools Save. When I uninstalled it, the problem was resolved. My understanding is that the ComfyUI frontend upgrade to version 1.16 changed the workflow reading process, and this change conflicted with how Cry Tools Save handles workflow formats, leading to issues with reading all workflows.

Also here, can reproduce this issue when running comfy with this params = running frontend version 1.16 then Cry Tools Save causing the mentioned graph.nodes error:

.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build --front-end-version Comfy-Org/ComfyUI_frontend@latest
pause

Will report to crystools repo...

Thanks for this post, was a big time saver

**Comment by Progresor-Kiseli** [comment]
> crystool save

That saved me as well. Thank you.

**Comment by dublaboy** [comment]
Thanks for the tip, I had he same proglem, disabled Crystools an voila, problem "dissapeared".

**Comment by showbert7** [comment]
> > In my case, the conflict was caused by crystools, crystool save and prompt_gallery.
> 
> Yes, I uninstall crytools save and fix the workflow's error, tks. CryTools_save nodes conflict.

its work for me too . thanks man
