### ISSUE TITLE
Broken Settings Menu

### ISSUE THREAD

**Issue by Djanghost** [comfyanonymous/ComfyUI#8381]
### Expected Behavior

Being able to scroll and select an option in any menu of the settings tab.

### Actual Behavior

It seems there is a big problem with the UI. I did a fresh install, comfy was installed in french for some reasons and I can't select “english” as language. As on the picture, all the menus are displayed in the background and impossible to access. That's what happens to all the drop-down menus.

![Image](https://github.com/user-attachments/assets/00bd386e-8fb2-458b-a152-d744736b98aa)

![Image](https://github.com/user-attachments/assets/2e53e5ca-ffbd-4297-9c49-5cddc3e8be7b)

### Steps to Reproduce

Click on any menu in the settings tab.

### Debug Logs

```powershell
This is an UI error.
```

**Comment by comfyui-wiki** [comment]
https://docs.comfy.org/troubleshooting/custom-node-issues

please refer to the troubleshooting docs to disable all custom nodes and see if it still happens

**Comment by comfyui-wiki** [comment]
Seems it's an issue with the FE 1.12.3

**Comment by Djanghost** [comment]
> https://docs.comfy.org/troubleshooting/custom-node-issues
> 
> please refer to the troubleshooting docs to disable all custom nodes and see if it still happens

It does the same thing by disabling all custom nodes. The temporary trick I've found is to click once on the drop-down menu and use the keyboard arrows blindly, pressing “enter” until I find the right drop-down menu option I want.

**Comment by comfyui-wiki** [comment]
It's a bug with the FE v1.12.3, which  should be fixed once relevant PR  has been merged

**Comment by Djanghost** [comment]
> It's a bug with the FE v1.12.3, which should be fixed once relevant PR has been merged

It's still doesn't work even after updating the frontend

**Comment by webfiltered** [comment]
Thanks for the update!  Looking into it.

**Comment by Djanghost** [comment]
The display problem is still present unfortunatly, and all these updates tend to break other important node too.

**Comment by webfiltered** [comment]
The issue is resolved and tested in various configurations.

If you still have the issue on 1.21.6, please open an issue on the frontend repo.

https://github.com/Comfy-Org/ComfyUI_frontend/issues
